# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GeekTime' do
  # use_frameworks!

 pod 'CYLTabBarController', '~> 1.17.6'
 pod 'AFNetworking', '~> 3.1.0'
 pod 'SDWebImage', '~> 4.2.3'
 pod 'SDAutoLayout', '~> 2.2.0'
 pod 'Bugly', '~> 2.5.0'
 pod 'MJRefresh', '~> 3.1.15.1'
 pod 'MJExtension', '~> 3.0.13'
 pod 'IQKeyboardManager', '~> 5.0.7'
 pod 'SVProgressHUD', '~> 2.2.2'
end
